download the latest bugfix version

> git clone http://luajit.org/git/luajit-2.0.git

goto src and type

> mingw32-make

copy lua51.dll and luajit.exe to bin (they come stripped)

copy jit folder to root (optional, for jit output)
